set_property SRC_FILE_INFO {cfile:C:/Users/za10196/Desktop/project_lab10/project_lab10.srcs/constrs_1/new/constraint.xdc rfile:../../../project_lab10.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports rst]
